### ISSUE TITLE
Can't install with composer and PHP 8.2.x

### ISSUE THREAD

**Issue by jeffshaikh** [BrightLocal/apiclient-php#3]
When trying to install using composer using

` composer require brightlocal/apiclient-php`

the following error message: 

Cannot use brightlocal/apiclient-php's latest version 1.0.0 as it requires php ^7.4 which is not satisfied by your platform.
In PackageDiscoveryTrait.php line 317:
Package brightlocal/apiclient-php has requirements incompatible with your PHP version, PHP extensions and Composer version:
    - brightlocal/apiclient-php 1.0.0 requires php ^7.4 which does not match your installed version 8.2.0.

**Comment by alnarozhny** [comment]
PHP version updated in a new release.
